version: '3'

services:
  server:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
        - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
        - ./app:/var/www/app

  php:
    build:
      context: .
    volumes:
      - ./app:/var/www/app

  db:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'password'
      MYSQL_DATABASE: 'superlogica'
    volumes:
      - ./db/setup.sql:/docker-entrypoint-initdb.d/setup.sql
    ports:
       - 3306:3306